### ISSUE TITLE
建议: 升级一下 package-lock.json

### ISSUE THREAD

**Issue by hikerpig** [corvofeng/Vsnips#15]
似乎只停留在 version 0.1.0 ，理论上每次 npm i 都应该更新的才对。

目前的问题是，package-lock.json 里缺了一些 package.json 里有的依赖项。

之前我加过一些依赖，不过不敢直接跨了好多版本更新 package-lock.json，不知道你那边有什么别的考虑。麻烦你自己确认一下没什么问题更新一下。

**Comment by corvofeng** [comment]
c48282accb043f8447de3d15599b559ed6fb8614
