### ISSUE TITLE
Mac中无法使用原有的ultisnips片段

### ISSUE THREAD

**Issue by BerryTaylor** [corvofeng/Vsnips#17]
我的vsnips配置和片段设置如图所示。但是在tex和vim文件中都没法使用原有的片段，没有反应。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52693674/73999041-784a0a00-499e-11ea-969b-19978ea1c3f4.png">
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/52693674/73999072-8861e980-499e-11ea-98c5-67cd1556fffa.png">

**Comment by corvofeng** [comment]
你有试过这样用吗: `/home/corvo/.vim/UltiSnips`

不要将家目录缩写成`~`, 而是完整的补全出来, 稍后我会看看有没有办法处理一下.

**Comment by BerryTaylor** [comment]
你好，
即便我按照您的说明去书写，如图，
还是无法使用自己的片段。系统是

设置现在是

vscode是最新版。

**Comment by BerryTaylor** [comment]
你好，
即便我按照您的说明去书写，如图，
还是无法使用自己的片段。系统是
![image](https://user-images.githubusercontent.com/52693674/74031612-f0d7b780-49ec-11ea-9fad-8cc4b6afe77c.png)
设置现在是
![image](https://user-images.githubusercontent.com/52693674/74031627-f7fec580-49ec-11ea-808b-d625a06d07c2.png)
vscode是最新版。

**Comment by corvofeng** [comment]
你改过设置之后有试着重启了吗, 如果重启没成功

可以临时设置一下:

```json
{
    "Vsnips.LogLevel": "DEBUG",
}
```
然后帮我查看一下日志文件吗`~/Library/Preferences/Vsnips/vsnips.log`

**Comment by BerryTaylor** [comment]
当然，这是获得的文件。软件已经重启若干次了。

**Comment by corvofeng** [comment]
我没有办法查看这个文件
![image](https://user-images.githubusercontent.com/12025071/74032944-1b773f80-49f0-11ea-946b-99d05237f4d7.png)

你看看有没有办法发给我, 或者到这里试试:

https://gitter.im/corvofeng/Vsnips

**Comment by corvofeng** [comment]
已经保证补全时加载了所有片段, 这个issue关掉了
