### ISSUE TITLE
[问题] mac 下 , vscode  市场  v0.2.9 版功能无法使用

### ISSUE THREAD

**Issue by hikerpig** [corvofeng/Vsnips#2]
使用 VSCodium,  1.41.0
Vsnips: v0.2.9 版本

在 `settings.json` 里配置了目录。

```json
{
  "Vsnips.SnipsDir": ["/Users/hikerpig/.vim/Ultisnips"],
  "Vsnips.VarFiles": ["/Users/hikerpig/.vimrc"]
}
```

然后怎么开启 expand 功能呢？

哦还有, command 会报错 "command 'extension.edit_vsnips' not found"

**Comment by hikerpig** [comment]
看了一下 log, 好像是因为这里报错了, 我的系统是 OSX 10.15, 有办法修复么？

![image](https://user-images.githubusercontent.com/2259688/71167322-72358800-228f-11ea-8f15-96ce81841075.png)

**Comment by corvofeng** [comment]
> 看了一下 log, 好像是因为这里报错了, 我的系统是 OSX 10.15, 有办法修复么？
> 
> ![image](https://user-images.githubusercontent.com/2259688/71167322-72358800-228f-11ea-8f15-96ce81841075.png)

这个问题是在mac下创建的配置文件夹有问题, 应该要创建`~/Preferences/Vsnips`, 我发了新版, 可以稍后看下解决了没有.

**Comment by hikerpig** [comment]
问题已解决，感谢。
多说一句，其实这种拼路径的事情用一下 `path.join` 能减少心智负担和手误可能。
