### ISSUE TITLE
[Nit] Typo (languate -> language)

### ISSUE THREAD

**Issue by vgxbj** [corvofeng/Vsnips#21]
无意发现下栏的 language 好像写错了

![image](https://user-images.githubusercontent.com/21099318/74640852-3b0a2700-51ab-11ea-903a-67dd753acc59.png)

搜了一下
![image](https://user-images.githubusercontent.com/21099318/74640804-229a0c80-51ab-11ea-85db-9ff0f3e8ec4e.png)

**Comment by corvofeng** [comment]
感谢指出, 改过了哈, f508f8dfe32999d403a05c4998d49a37978232a4
