### ISSUE TITLE
试图创建markdown的补全片段，但是什么都没有发生

### ISSUE THREAD

**Issue by yfzhao20** [corvofeng/Vsnips#32]
试图给我的markdown文档创立代码片段，于是在`/corvofeng.vsnips-0.4.9/Ultisnips`文件夹下新建了`markdown.snippets` 。随后在其中加入了如下代码：
```
snippet dm "Math" wA
\[
$1
\] $0
endsnippet
```
然后回到`test.md` 中进行测试，输入`dm` ，**什么也没有发生…**…

而且插件自带的片段也不能用，此时我已经设置了启用默认片段。

而且有时候会出现End add language snippet，感觉不知道什么阻止了代码片段……

请问如何进行相关配置？

**Comment by corvofeng** [comment]
这个issue中提到了几个问题, 我分别说一下

**Comment by corvofeng** [comment]
首先, 如果没有显式代码片段, 可能是根本没有添加成功, vsnip是依靠正则解析的, 所以, 确保文件是`LF`作为换行符

![image](https://user-images.githubusercontent.com/12025071/117522103-197da100-afe4-11eb-83ec-3a27ae925fc9.png)

修改了之后请reload window或是重启vscode, 使用快捷键可以查看当前文件可用的代码片段, 例如,

![image](https://user-images.githubusercontent.com/12025071/117522185-75482a00-afe4-11eb-9f73-22d9dd856c84.png)


![image](https://user-images.githubusercontent.com/12025071/117522197-81cc8280-afe4-11eb-8a9b-43fd6fbcbd03.png)

下面是我这里的使用效果

![Peek 2021-05-08 10-04](https://user-images.githubusercontent.com/12025071/117522249-d7089400-afe4-11eb-99a1-fe87688b23d8.gif)
![Peek 2021-05-08 10-07](https://user-images.githubusercontent.com/12025071/117522314-39fa2b00-afe5-11eb-902b-b85ade115d47.gif)

**Comment by corvofeng** [comment]
我平时使用的是Linux, 刚刚用Windows测试了下,  虽然无法提示, 但是可用的片段里面是有的, 首先你需要确定下可用的代码片读是不是有

![image](https://user-images.githubusercontent.com/12025071/117522348-6ada6000-afe5-11eb-939f-adb4aa111788.png)

**Comment by corvofeng** [comment]
出现End add language snippet 是正常的现象, 我用来提醒用户已经加载好了代码片段

**Comment by yfzhao20** [comment]
感谢解答！可是我添加片段、刷新窗口之后，甚至可用代码片段都加载不出来：



但是很奇怪，在.c的文件中使用就可以：



可能我使用的姿势不对？原snippet文件的换行符也改成了LF，但是还是没有奏效。






发件人: 一枚小猿
发送时间: 2021年5月8日 10:08
收件人: corvofeng/Vsnips
抄送: yfzhao20; Author
主题: Re: [corvofeng/Vsnips] 试图创建markdown的补全片段，但是什么都没有发生 (#32)

首先, 如果没有显式代码片段, 可能是根本没有添加成功, vsnip是依靠正则解析的, 所以, 确保文件是LF作为换行符

修改了之后请reload window或是重启vscode, 使用快捷键可以查看当前文件可用的代码片段, 例如,


下面是我这里的使用效果

**Comment by yfzhao20** [comment]
试验中还出现了其他现象：
1.

似乎出现了这个之后，才能在markdown下使用片段，也就是加载可能需要一些时间？

2.

我开启了这个，但是似乎并没有什么效果，对于上次发的自定义片段，输入dm之后并不会自动展开……

3.代码片段似乎不太“干净”

前三行是内置的代码提示。后面是用插件定义的snippet，看出来前面有vsnips的提示，后面有名称。能否有办法把这个去掉？（我觉着对我来说不必标出vsnip的标识）

4.下面这个box是想来做什么？是不想用来构造一个框，但是源码怎么上去了。倒是vbox能上去一个框




发送自 Windows 10 版邮件应用

发件人: 一枚小猿
发送时间: 2021年5月8日 10:22
收件人: corvofeng/Vsnips
抄送: yfzhao20; Author
主题: Re: [corvofeng/Vsnips] 试图创建markdown的补全片段，但是什么都没有发生 (#32)

出现End add language snippet 是正常的现象, 我用来提醒用户已经加载好了代码片段

**Comment by corvofeng** [comment]
你用邮件发的评论是没有图的, 可以在issue里面添加图片吗?

**Comment by yfzhao20** [comment]
以下是邮件全文

可是我添加片段、刷新窗口之后，甚至可用代码片段都加载不出来：
![111](https://user-images.githubusercontent.com/80528249/117525349-6b2e2780-aff4-11eb-8d14-f8065410b7fc.gif)

但是很奇怪，在.c的文件中使用就可以：

![122](https://user-images.githubusercontent.com/80528249/117525356-71bc9f00-aff4-11eb-8f8c-793314c2860b.gif)

可能我使用的姿势不对？原snippet文件的换行符也改成了LF，但是还是没有奏效。


试验中还出现了其他现象：
1.
![image](https://user-images.githubusercontent.com/80528249/117525377-96b11200-aff4-11eb-9195-b3539378c5a7.png)

似乎出现了这个之后，才能在markdown下使用片段，也就是加载可能需要一些时间？

2.
![image](https://user-images.githubusercontent.com/80528249/117525383-9e70b680-aff4-11eb-9dbc-5aacc315ef1e.png)

 
我开启了这个，但是似乎并没有什么效果，对于上次发的自定义片段，输入dm之后并不会自动展开……

3.代码片段似乎不太“干净”
![image](https://user-images.githubusercontent.com/80528249/117525400-b21c1d00-aff4-11eb-8e47-c990b00e83e7.png)
前三行是内置的代码提示。后面是用插件定义的snippet，看出来前面有vsnips的提示，后面有名称。能否有办法把这个去掉？（我觉着对我来说不必标出vsnip的标识）

4.下面这个box是想来做什么？是不想用来构造一个框，但是源码怎么上去了。倒是vbox能上去一个框
![4](https://user-images.githubusercontent.com/80528249/117525409-bcd6b200-aff4-11eb-9063-bbf57d6d2182.gif)

**Comment by corvofeng** [comment]
1. 为了启动vscode比较快, 所以vsnips做了懒加载, 第一次载入markdown文件的时候, 才会去加载
2. 在我试验的时候, 在我的linux系统中, dm可以自动展开 
![](https://user-images.githubusercontent.com/12025071/117522314-39fa2b00-afe5-11eb-902b-b85ade115d47.gif)
windows中我始终没法触发补全操作, 可能我要自己再调试一下, 我是想说, 自动展开功能是有的

3. 这个是vsnip的标识, 我可以考虑允许配置是否显示
4. box这个功能是因为ultisnips自带的, 也没办法转译, 所以加了vbox, 这个功能经过特殊处理, 用于产生box片段 #4 
![](https://user-images.githubusercontent.com/12025071/72673114-c014fa00-3aa0-11ea-8bdf-e46adefdbe2a.gif)

**Comment by yfzhao20** [comment]
感谢解答！至少现在在插件加载完成之后，可以通过tab选择了。

另外的一些问题：

1. 是否支持上下文环境？按照这位小哥的办法（ https://cloud.tencent.com/developer/article/1527428 ），通过读取语法突出显示，来确定是否应该展开。这个对LaTeX或者markdown中的数学环境很有用。
![image](https://user-images.githubusercontent.com/80528249/117529657-54df9600-b00b-11eb-980a-115a02869aa5.png)


2. 在使用hsnip（ https://github.com/draivin/hsnips ）时，自动展开是可以用的。是否有触发机制上的不同？
![4](https://user-images.githubusercontent.com/80528249/117529804-61b0b980-b00c-11eb-9cf0-850b25c9ebde.gif)

当然这个插件使用JavaScript编写，原生的vim片段有些水土不服，需要转写成js。

**Comment by corvofeng** [comment]
1. vsnip是可以获取上下文信息的吧,  但是你可能要自己用js重新实现一遍了
  
   https://vsnips.corvo.fun/zh/example_snips/#_3

2. 自动展开功能的不可用可能你不同环境的问题, 可能是一些bug导致了不可用, 我记得我读过hsnips的代码, 触发机制应该是一样的, 但是我觉得对性能影响比较大, 所以不喜欢这个功能, 默认也不开

**Comment by corvofeng** [comment]
是个人偏好的原因, 我希望能看到代码片段是谁提供的, 你的建议会我考虑的. 希望这个插件能提高你的效率

**Comment by corvofeng** [comment]
已经去掉了`Vsnips-`的前缀, 希望你用的时候可以看到
