### ISSUE TITLE
VBox 删除后输入新内容会错乱

### ISSUE THREAD

**Issue by pilgrimlyieu** [corvofeng/Vsnips#37]
![10](https://user-images.githubusercontent.com/80107081/133891225-a06106b7-c1da-4cd2-862d-9e3494796363.gif)

**Comment by corvofeng** [comment]
问题在我这里也能复现, 我尝试修复下

**Comment by corvofeng** [comment]
问题已经修过了, 你可以试试

**Comment by pilgrimlyieu** [comment]
已经工作正常了！非常感谢。
