### ISSUE TITLE
How to use UltiSnips?

### ISSUE THREAD

**Issue by narimiran** [corvofeng/Vsnips#39]
I'm trying to follow the instructions posted here: https://github.com/corvofeng/Vsnips#how-to-use-vsnips but I'm not able to make it work.

This is what I have put in my `settings.json`:

```json
    "Vsnips.SnipsDir": [
        "~/.config/nvim/my_snippets",
        "~/.config/nvim/plugged/vim-snippets/UltiSnips",
    ],
    "Vsnips.VarFiles": [
        "~/.config/nvim/init.vim"
    ]
```

Directory `~/.config/nvim/my_snippets` contains three files: `nim.snippets  python.snippets  racket.snippets`, but none of them is picked up.
Directory `~/.config/nvim/plugged/vim-snippets/UltiSnips` contains lots of snippet files available at https://github.com/honza/vim-snippets/tree/master/UltiSnips

Can you tell me what I'm doing wrong and how can I make those snippets work with your plugin?

**Comment by corvofeng** [comment]
1. When I use racket.snippets.

it works, I need to add 
![image](https://user-images.githubusercontent.com/12025071/138537374-f400110f-9357-4fa7-9643-e72b17b39a52.png)

Make sure that vscode detects the right languageId.

![image](https://user-images.githubusercontent.com/12025071/138537410-c6a90e52-d03e-4490-87a9-0e29aa02b9aa.png)

And add the config:

```json
{
    "Vsnips.SnipsDir": [
        "/home/corvo/.vim/UltiSnips"
    ],
}
```

```
/home/corvo/.vim/UltiSnips
├── all.snippets
├── racket.snippets
└── vimwiki.snippets
```

![image](https://user-images.githubusercontent.com/12025071/138537404-e95c2e10-d83e-4fe1-a7dc-bca5ff7c28f5.png)

![image](https://user-images.githubusercontent.com/12025071/138537486-806d901e-653d-457f-90c5-7bb6e426d685.png)

**Comment by Ynfiniti** [comment]
> I've changed log level and suddenly Python and Nim snippets started working!? I think it is a strange coincidence, but it worked.

It is not a coincidence! I had the same problem but with a Latex File.
I have Latex Workshop installed (Maybe related to [this issue](https://github.com/corvofeng/Vsnips/issues/25).
Vsnips couldn't determine the filetype even tho VSCode clearly does.
![image](https://user-images.githubusercontent.com/38784440/197075030-1323479f-7bcb-414a-8b6c-07fd7d72cb80.png)

This Problem resolved after adding the line `"Vsnips.LogLevel": "DEBUG",` to the settings.json and all the snippets work fine now.

**Comment by corvofeng** [comment]
@Ynfiniti  How can I reproduce your problem? Have you tried to use `show available snippets`?


![image](https://user-images.githubusercontent.com/12025071/197514753-43dd02f6-9c96-4eaa-8e54-ee5d5b0ce3b5.png)

**Comment by Ynfiniti** [comment]
> How can I reproduce your problem? Have you tried to use `show available snippets`?

Yes I did try `show available snippets`and it does not work (doesn't give any results). 
On the other hand, `edit snippets` does show that all the snippets are loaded and correct.
Just after adding the line `"Vsnips.LogLevel": "DEBUG",` VSnips was able to detect the latex filetype at all.
Without it, the plugin always showed the message: `End add language all` on the bottom of VSCode, for every .tex file.
![image](https://user-images.githubusercontent.com/38784440/197075585-cff32f2f-5a07-4552-acf4-e75e9cafd256.png)

Don't know if it helps in any way, but these are my current settings
![image](https://user-images.githubusercontent.com/38784440/197519484-fd55b3e3-f945-4a77-bcb9-b5e7e908bee0.png)

**Comment by corvofeng** [comment]
I found an error in the console. There is a temporary solution: Change filetype to `TeX`.


```
2022-10-24 20:33:54: [I] Get latex available snippet

/home/xxxx/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/workbench/api/node/extensionHostProcess.js:94
rejected promise not handled within 1 second: The latex does't add yet
```

![image](https://user-images.githubusercontent.com/12025071/197532005-8030d0d7-6ea4-400c-bfba-7be875f0d00c.png)
