### ISSUE TITLE
求助Vsnips插件不作用的情况

### ISSUE THREAD

**Issue by Chiron19** [corvofeng/Vsnips#40]
为何配置了latex.snippets和tex.snippets但是均不能在tex中作用？
在工作区中的c，python等Vsnips可以正常工作，
但是latex文件却不行（Show available snippets只呈现all.snippets里面的snips）。
安装的相关插件有LaTeX language support，LaTeX Workshop和latex-formatter

setting部分的配置如下:
```json
"Vsnips.IgnoredSnippets": [],
    "Vsnips.UseDefaultSnips": false,
    "Vsnips.EnableAutoTrigger": true,
    "Vsnips.SnipsDir": [
        "Ultisnips",
        "C:\\Users\\surface\\.vscode\\extensions\\corvofeng.vsnips-0.5.6\\Ultisnips"
    ],
    "Vsnips.UserScriptFiles": [
        "C:\\Users\\surface\\.vscode\\extensions\\corvofeng.vsnips-0.5.6\\Ultisnips\\latex.snippets"
    ],
    "Vsnips.VarFiles": [
        "/home/corvo/.vimrc",
        "/home/corvo/.vim/common.vim",
    ],
```

求解决方法。感谢❤

**Comment by corvofeng** [comment]
首先, 如果没有显式代码片段, 可能是根本没有添加成功, vsnip是依靠正则解析的, 所以, 确保文件是`LF`作为换行符

![image](https://user-images.githubusercontent.com/12025071/117522103-197da100-afe4-11eb-83ec-3a27ae925fc9.png)

**Comment by corvofeng** [comment]
#32  你看下这个是不是能解决你的问题

**Comment by Chiron19** [comment]
Thanks a lot! The problem has been solved successfully under the instruction and another issue given by you. 😊

> #32 你看下这个是不是能解决你的问题
